version: '3.8'

services:
  mobile-app:
    build: .
    container_name: simple-todo-app
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    stdin_open: true
    tty: true
    networks:
      - mobile-network

networks:
  mobile-network:
    driver: bridge